name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maven-verify:
    name: "Build and run tests"
    strategy:
      matrix:
        java: [8, 11, 16]
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2
    - name: "Set up Java"
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: "adopt"
    - name: "Get Maven dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: "Build with Maven"
      run: mvn --batch-mode verify
  maven-deploy:
    name: "Deploy snapshot to Maven Central"
    needs: maven-verify
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2
    - name: "Setup Java"
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: "adopt"
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_TOKEN
    - name: "Check Maven Settings"
      run: cat /home/runner/.m2/settings.xml
    - name: "Get Maven dependencies from cache"
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: "Check Maven Settings"
      run: cat /home/runner/.m2/settings.xml
    - name: "Build and deploy to the Maven Central Repository"
      run: mvn --batch-mode -DskipTests deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}